const AccountController = require('../controllers/UserController');
const UploadController = require('../controllers/UploadController');
const VideoController = require('../controllers/VideoController');
module.exports = (server) => {
  server.route('/userCreate')
    .post(AccountController.createUser)
  server.route('/loginUser')
    .post(AccountController.loginUser)
  server.route('/mongoLogin')
    .post(AccountController.mongoLogin)
  server.route('/getUsername')
    .get(AccountController.getUsername)
  server.route('/getUserID')
    .get(AccountController.getUserID)
  server.route('/logoutUser')
    .get(AccountController.logoutUser)
  server.route('/uploadProfilePic')
    .post(UploadController.deleteProfileImage, UploadController.uploadProfileImage)
  server.route('/getBucketList')
    .get(UploadController.listAllBucketObjects)
  server.route('/getUserImage')
    .get(UploadController.getUserImage)
  server.route('/addDefaultPic')
    .post(UploadController.addDefaultPic)
  server.route('/uploadVideo')
    .post(VideoController.uploadVideo)
  server.route('/getVideoList')
    .get(VideoController.getVideoList)
  server.route('/getAllVideos')
    .get(VideoController.getAllVideos)
  server.route('/getVideo')
    .post(VideoController.getVideoByID)
  server.route('/deleteVideos')
    .post(VideoController.deleteVideos)
  server.route('/addComment')
    .post(VideoController.addComment)
  server.route('/addReplies')
    .post(VideoController.addReplies)
}